# See LICENSE file for copyright and license details.

before_install:
  - yes | sudo add-apt-repository ppa:hansjorg/rust
  - sudo apt-get update

install:
  - sudo apt-get install rust-nightly
  - sudo apt-get install libXxf86vm-dev

script:
  - mkdir deps
  - cd deps

  # Install glfw lib
  - git clone --depth=1 https://github.com/glfw/glfw.git
  - cd glfw
  - cmake -DBUILD_SHARED_LIBS=ON
  - make glfw # build only .so files
  - cp src/libglfw.so* .. # copy dynamic libraries
  - cd ..

  # Install glfw-rs
  - git clone --depth=1 https://github.com/bjz/glfw-rs
  - rustc --dylib glfw-rs/src/lib.rs --out-dir .

  # Install gl-rs
  - git clone --depth=1 https://github.com/bjz/gl-rs
  - rustc --dylib gl-rs/src/gl/lib.rs --out-dir .

  # Install cgmath-rs
  - git clone --depth=1 https://github.com/bjz/cgmath-rs
  - rustc --dylib cgmath-rs/src/cgmath/lib.rs --out-dir .

  # Return from 'deps' dir
  - ..

  # Build Marauder
  - make
