# See LICENSE file for copyright and license details.

before_install:
  - yes | sudo add-apt-repository ppa:hansjorg/rust
  - sudo apt-get update

install:
  - sudo apt-get install rust-nightly
  - sudo apt-get install libXxf86vm-dev

script:
  # Download, build and install dependencies
  - ./make_deps.sh

  # Build Marauder
  - make
