# See LICENSE file for copyright and license details.

language: rust

install:
    - sudo apt-get install libXxf86vm-dev
    - git clone --depth=1 https://github.com/ozkriff/marauder-data target/data

# vim: set tabstop=4 shiftwidth=4 softtabstop=4 expandtab:
